### ISSUE TITLE
Rendering dynamic fonts or SVG output

### ISSUE THREAD

**Issue by knowBalpreet** [friday/lottie-node#5]
hey @friday  thanks for putting your code here. This is a great way to create templates and render on the server. 
The problem i have is that if I chose canvas as renderer, I am not able to change text on runtime as it converts text to glyphs and during template creation i am not sure of what all characters to put in hidden layer as suggested by bodymovin. Also there is some issue with masking but that can be taken of during creation.

And if i chose svg as renderer, i cannot export frames as png (i can export them as svg though) on nodejs.

```
let data = "data:image/svg+xml;base64,";
            let svgString = anim.renderer.svgElement.outerHTML;
            let base64 = window.btoa(svgString);
            let dataURI = data + base64;
```

Now if i use img onload method to actually use this dataURI as source for image i get error.

Also wanted to know what actually context in rendererSettings does in loadAnimation. Does it writes to the context of canvas on its own? I am not sure how it works.

Any help would be appreciated. thanks again for sharing your library.

**Comment by friday** [comment]
Yes. If you export an animation with the text "Hello", you can change the text in the json/data, but only as long as the new characters are either "H", "e", "l", or "o". To support other characters you have to export with a [hidden layer](https://github.com/airbnb/lottie-web/issues/146#issuecomment-248846841) containing all the characters you could possibly want to use later, so that they are converted to glyphs.

Here's a set of typeable English and latin characters:

```
!"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|} ~€‚ƒ„…†‡ˆ‰Š‹ŒŽ‘’“”•–—˜™š›œžŸ¡¢£¤¥¦§¨©ª«¬®¯°±²³´µ¶·¸¹º»¼½¾¿ÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖ×ØÙÚÛÜÝÞßàáâãäåæçèéêëìíîïðñòóôõö÷øùúûüýþÿ\n
```

For something more generic you would want to include Spanish and French letters. If you want to support non-latin languages, the set will grow significantly, and your font would have to include them too.

In your Bodymovin export you also need to Check the "Glyphs" and "Hidden" (layers) options

Lottie's SVG renderer isn't like traditional flat SVG images. They're animated after all. While the canvas is animated too, the difference is it has built in capability (also supported by node-canvas) for exporting frames.

Edit: Found a better character set.

**Comment by knowBalpreet** [comment]
Hey @friday  thanks for getting back so quick.

I feel if i can just somehow load datauri in the image and use context draw image method to write on canvas and then export as png from the canvas.toBuffer method then it can be done. 

But I cannot find a workaround for loading images. this works perfectly in the browser though. the other strategy I can think of is to use the headless browser. but I think the solution based on node js will be faster. 

Do you have any idea what does context parameter does in rendererSettings? I think it uses an existing canvas to draw on it. Or not maybe.

**Comment by friday** [comment]
Images should work, and hasn't been a problem for us. The url should be a path. The "file://"-protocol is supported by node-canvas I think, but probably not by lottie-node since we have handle image loading separately.

You could log the `assetPath` here to verify it's correct: https://github.com/friday/lottie-node/blob/master/index.js#L11

**Comment by friday** [comment]
Seems like I missed the data-uris-part.

I haven't tested data-uris. You'd want to convert to a buffer. Something like: `Buffer.from(uri.replace(/^data:\w+\/\w+;base64,/, ''), 'base64')`.

Since the lottie-node code is very small I suggest hacking it to add support for features you need and PR if you think others will need them too.

> Do you have any idea what does context parameter does in rendererSettings? I think it uses an existing canvas to draw on it. Or not maybe.

You create the canvas externally and pass [context](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D) to Lottie so that Lottie can draw on the canvas. This isn't really a lottie-node question. The Lottie web API is documented in the [wiki](https://github.com/airbnb/lottie-web/wiki/Renderer-Settings#context).

**Comment by friday** [comment]
Closing this, since there's no clear action, issue or suggestion. Lottie-node is just a wrapper, and doesn't handle replacing texts or glyphs.
